const LOAD_EVENTS = `LOAD_EVENTS`;
const DELETE_EVENT = `DELETE_EVENT `;
const ON_EVENT_DELETE = `ON_EVENT_DELETE `;
const CLOSE_POPUP = 'CLOSE_POPUP';
const GET_PARTICIPANT_FROM_FILTER = 'GET_PARTICIPANT_FROM_FILTER';
const GET_AUTH_USER = 'GET_AUTH_USER';
const LOGIN = 'LOGIN';
const POST_NEW_EVENT = 'POST_NEW_EVENT';
const SHOW_NEW_EVENT_FORM = 'SHOW_NEW_EVENT_FORM';
const CHECK_DUPLICATE = 'CHECK_DUPLICATE';

export {
  LOAD_EVENTS,
  ON_EVENT_DELETE,
  DELETE_EVENT,
  CLOSE_POPUP,
  GET_PARTICIPANT_FROM_FILTER,
  GET_AUTH_USER,
  LOGIN,
  POST_NEW_EVENT,
  SHOW_NEW_EVENT_FORM,
  CHECK_DUPLICATE,
};
